export const Route = {
  home: '/',
  about: '/about',
  adopt: '/adopt',
  bePart: '/be-part',
  login: '/login',
  contact: '/contact',
  donate: '/donate',
  userRegistration: '/user-resistration',
  profile: '/profile',
  myPets: 'my-pets',
  donations: 'donations',
  adopters: 'adopters',
  animals: 'animals',
  animalRegistration: '/animal-resistration',
  animalDetails: (id: number | string) => `/animal-details/${id}`,
};
